# values.yaml

# In charts/docker-registry/values/k3d-my-cluster.yaml
configData:
  http:
    headers:
      X-Content-Type-Options: [nosniff]
  # Add these settings to handle large uploads
  compatibility:
    schema1:
      enabled: true
  validation:
    disabled: true
  maxUploadSize: 20000M  # Adjust based on your needs


# Secrets for basic authentication (htpasswd)
secrets:
  htpasswd: "leo:$2y$05$8o3j4damOS8Lvl0LSHHl1ecCb8p.7vssHVsxOgmMNGFUylqng2MEW"

# Ingress configuration
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP" # Ensure NGINX uses HTTPS to communicate with the backend
    nginx.ingress.kubernetes.io/ssl-redirect: "true" # Redirect HTTP to HTTPS
    nginx.ingress.kubernetes.io/proxy-body-size: "0" 
  hosts:
    - registry.localk8s.localdomain # List of hostnames (must be strings)
  paths:
    - path: /
      pathType: Prefix
  tls:
    - secretName: wildcard-tls # Use the wildcard certificate for TLS termination
      hosts:
        - registry.localk8s.localdomain
