repositories:
  # trivy
  - name: trivy-operator
    url: https://aquasecurity.github.io/helm-charts 
  #sigstore 
  - name: sigstore
    url: https://sigstore.github.io/helm-charts
  #twuni
  - name: twuni
    url: https://helm.twun.io
